// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8QCVP8zk0CiSK4yhucLHWws5vOw4TJlY',
    appId: '1:180415661303:web:ed5f8d2145bda431267ff2',
    messagingSenderId: '180415661303',
    projectId: 'fir-firebase-chat-ddeb5',
    authDomain: 'fir-firebase-chat-ddeb5.firebaseapp.com',
    storageBucket: 'fir-firebase-chat-ddeb5.appspot.com',
    measurementId: 'G-YX96N6KRVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZH1IH_CDNBV1S06vFjUzOc2Daqd_ms5g',
    appId: '1:180415661303:android:3966efd12efdb20d267ff2',
    messagingSenderId: '180415661303',
    projectId: 'fir-firebase-chat-ddeb5',
    storageBucket: 'fir-firebase-chat-ddeb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQA7TfeoXZ28Xu9nYafJu1MxhgwngWCxE',
    appId: '1:180415661303:ios:82b14c90f4d10675267ff2',
    messagingSenderId: '180415661303',
    projectId: 'fir-firebase-chat-ddeb5',
    storageBucket: 'fir-firebase-chat-ddeb5.appspot.com',
    androidClientId: '180415661303-2j332rq7fsgctiqrci372fqa41pb3b55.apps.googleusercontent.com',
    iosClientId: '180415661303-m766f1amvrffi1r3r00v69hf6hok96q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFirebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQA7TfeoXZ28Xu9nYafJu1MxhgwngWCxE',
    appId: '1:180415661303:ios:e06396a21b451f3c267ff2',
    messagingSenderId: '180415661303',
    projectId: 'fir-firebase-chat-ddeb5',
    storageBucket: 'fir-firebase-chat-ddeb5.appspot.com',
    androidClientId: '180415661303-2j332rq7fsgctiqrci372fqa41pb3b55.apps.googleusercontent.com',
    iosClientId: '180415661303-5h180fqnki2hp6q92qa94p673piat8eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFirebaseChat.RunnerTests',
  );
}
